---
swagger: '2.0'
info:
  title: Dental X-ray Inference API
  description: API to infer information from dental X-ray images.
  version: 1.0.0
paths:
  "/periodontal_measure":
    post:
      summary: Infer Dental Xray
      operationId: infer_dental_xray_periodontal_measure_post
      x-google-backend:
        address: http://dentistry-inference-core-298229070754.asia-east1.run.app/periodontal_measure
      consumes:
      - multipart/form-data
      parameters:
      - name: scale
        in: query
        required: true
        type: string
        description: Scale
      - name: image
        in: formData
        required: true
        type: file
        description: Image
      responses:
        '200':
          description: Successful Response
          schema:
            "$ref": "#/definitions/InferenceResponse"
        '422':
          description: Validation Error
          schema:
            "$ref": "#/definitions/HTTPValidationError"
  "/Dental_segmentation":
    post:
      summary: Inference
      operationId: inference_Dental_segmentation_post
      x-google-backend:
        address: http://dentistry-inference-core-298229070754.asia-east1.run.app/Dental_segmentation
      consumes:
      - multipart/form-data
      parameters:
      - name: image
        in: formData
        required: true
        type: file
        description: Image
      responses:
        '200':
          description: Successful Response
          schema:
            "$ref": "#/definitions/YoloSegmentationResponse"
        '422':
          description: Validation Error
          schema:
            "$ref": "#/definitions/HTTPValidationError"
definitions:
  DentalMeasurements:
    type: object
    title: DentalMeasurements
    properties:
      side_id:
        type: integer
        minimum: 0
        title: Side Id
        description: Side ID must be a non-negative integer
      CEJ:
        type: array
        title: Cej
        items:
          type: integer
        minItems: 2
        maxItems: 2
      ALC:
        type: array
        title: Alc
        items:
          type: integer
        minItems: 2
        maxItems: 2
      APEX:
        type: array
        title: Apex
        items:
          type: integer
        minItems: 2
        maxItems: 2
      CAL:
        type: number
        minimum: 0
        title: Cal
        description: CAL must be a non-negative float
      TRL:
        type: number
        minimum: 0
        title: Trl
        description: TRL must be a non-negative float
      ABLD:
        type: number
        minimum: 0
        title: Abld
        description: ABLD must be a non-negative float
      stage:
        type: string
        enum:
        - '0'
        - '1'
        - '2'
        - '3'
        - I
        - II
        - III
        title: Stage
    required:
    - side_id
    - CEJ
    - ALC
    - APEX
    - CAL
    - TRL
    - ABLD
    - stage
  HTTPValidationError:
    type: object
    title: HTTPValidationError
    properties:
      detail:
        type: array
        title: Detail
        items:
          "$ref": "#/definitions/ValidationError"
  InferenceResponse:
    type: object
    title: InferenceResponse
    properties:
      request_id:
        type: integer
        title: Request Id
      measurements:
        type: array
        title: Measurements
        items:
          "$ref": "#/definitions/Measurements"
      message:
        type: string
        title: Message
    required:
    - request_id
    - measurements
    - message
  Measurements:
    type: object
    title: Measurements
    properties:
      teeth_id:
        type: integer
        title: Teeth Id
      pair_measurements:
        type: array
        title: Pair Measurements
        items:
          "$ref": "#/definitions/DentalMeasurements"
      teeth_center:
        type: array
        title: Teeth Center
        items:
          type: integer
        minItems: 2
        maxItems: 2
    required:
    - teeth_id
    - pair_measurements
    - teeth_center
  ValidationError:
    type: object
    title: ValidationError
    properties:
      loc:
        type: array
        title: Location
        items:
          type: string
      msg:
        type: string
        title: Message
      type:
        type: string
        title: Error Type
    required:
    - loc
    - msg
    - type
  YoloSegmentation:
    type: object
    title: YoloSegmentation
    properties:
      color_dict:
        type: object
        title: Color Dict
        additionalProperties:
          type: array
          items:
            type: integer
      class_names:
        type: object
        title: Class Names
        additionalProperties:
          type: string
      yolov8_contents:
        type: array
        title: Yolov8 Contents
        items:
          type: array
          items:
            type: number
    required:
    - color_dict
    - class_names
    - yolov8_contents
  YoloSegmentationResponse:
    type: object
    title: YoloSegmentationResponse
    properties:
      request_id:
        type: integer
        title: Request Id
      yolo_results:
        "$ref": "#/definitions/YoloSegmentation"
      message:
        type: string
        title: Message
    required:
    - request_id
    - yolo_results
    - message
