timeout: '3600s'  # é€™è£¡è¨­å®šç‚º 20 åˆ†é˜ï¼ˆ1200 ç§’ï¼‰
steps:
  - name: alpine
    entrypoint: sh
    args:
      - -c
      - 'echo "HUGGINGFACE_TOKEN=$$HUGGINGFACE_TOKEN"'
    secretEnv:
      - HUGGINGFACE_TOKEN
    id: DebugSecret

  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker buildx build --platform linux/amd64 --build-arg=HUGGINGFACE_TOKEN=$$HUGGINGFACE_TOKEN -t $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA -f Dockerfile .'
    id: Build
    secretEnv:
      - HUGGINGFACE_TOKEN
      
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--memory=32Gi'      
      - '--cpu=8'
      - '--timeout=900s'
      - '--quiet'
      - '--startup-probe=tcpSocket.port=8080,initialDelaySeconds=240,timeoutSeconds=240,failureThreshold=10,periodSeconds=240'
    entrypoint: gcloud

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Clean the Revisions'
    entrypoint: bash
    args:
      - -c
      - |
          echo "ðŸ” Listing recent revisions (including unhealthy ones)..."
          RAW_REVISIONS=$$(gcloud run revisions list \
            --service=$_SERVICE_NAME \
            --region=$_DEPLOY_REGION \
            --platform=managed \
            --format="value(metadata.name,status.conditions.type,status.conditions.status)" \
            --sort-by="~metadata.creationTimestamp" \
            --limit=10)

          echo "$$RAW_REVISIONS"

          echo "ðŸ§¹ Deleting unhealthy revisions..."
          echo "$$RAW_REVISIONS" | while read revision_line; do
            REV_NAME=$$(echo $$revision_line | awk '{print $$1}')
            CONDITION_TYPE=$$(echo $$revision_line | awk '{print $$2}')
            CONDITION_STATUS=$$(echo $$revision_line | awk '{print $$3}')

            if [ "$$CONDITION_TYPE" = "Ready" ] && [ "$$CONDITION_STATUS" != "True" ]; then
              echo "ðŸš« Deleting bad revision: $$REV_NAME"
              gcloud run revisions delete $$REV_NAME \
                --region=$_DEPLOY_REGION \
                --platform=managed \
                --quiet
            fi
          done

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Update Traffic'
    entrypoint: bash
    args:
      - -c
      - |
          echo "Getting the latest two active revisions..."
          REVISIONS=$$(gcloud run revisions list \
            --service=$_SERVICE_NAME \
            --region=$_DEPLOY_REGION \
            --platform=managed \
            --filter="status.conditions.type=Ready AND status.conditions.status=True" \
            --format="value(metadata.name)" \
            --sort-by="~metadata.creationTimestamp" \
            --limit=2)

          echo "$$REVISIONS"

          COUNT=$$(echo "$$REVISIONS" | wc -l)
          if [ "$$COUNT" -lt 2 ]; then
            echo "Error: Less than 2 active revisions found"
            exit 1
          fi

          LATEST_REVISION=$$(echo "$$REVISIONS" | head -n 1)
          OLD_REVISION=$$(echo "$$REVISIONS" | tail -n 1)

          echo "Updating traffic: $$LATEST_REVISION=10, $$OLD_REVISION=90"

          gcloud run services update-traffic $_SERVICE_NAME \
            --platform=managed \
            --region=$_DEPLOY_REGION \
            --to-revisions=$$LATEST_REVISION=10,$$OLD_REVISION=90

images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: dentistry-inference-core-2514
  _DEPLOY_REGION: asia-east1
  _AR_HOSTNAME: asia-east1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: sandbox-446907
  _TRIGGER_ID: 868da32c-0fe8-45e8-90fa-8b46110c3836
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - dentistry-inference-core-2514
availableSecrets:
  secretManager:
    - versionName: projects/298229070754/secrets/HUGGINGFACE_TOKEN/versions/latest
      env: HUGGINGFACE_TOKEN
#build test1