name: Main push rule pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    env:
      HUGGINGFACE_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Upgrade pip and install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Cache downloaded models (./models)
        uses: actions/cache@v4
        with:
          path: ./models
          key: ${{ runner.os }}-models-${{ hashFiles('src/allocation/service_layer/download.py') }}
          restore-keys: |
            ${{ runner.os }}-models-

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies with uv
        run: uv pip install -r requirements.txt

      - name: Download model to ./models
        run: uv pip run python ./src/allocation/service_layer/download.py
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Run tests with pytest
        run: uv pip run pytest --cov=src -vv tests/unit