name: Main push rule pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HUGGINGFACE_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache virtualenv
        uses: actions/cache@v3
        with:
          path: ~/.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Cache downloaded models (./models)
        uses: actions/cache@v3
        with:
          path: ./models
          key: ${{ runner.os }}-models-${{ hashFiles('src/allocation/service_layer/download.py') }}
          restore-keys: |
            ${{ runner.os }}-models-

      - name: Install dependencies
        run: |
          python -m venv ~/.venv
          source ~/.venv/bin/activate
          pip install -r requirements.txt

      - name: Download model to ./models
        run: |
          ~/.venv/bin/python ./src/allocation/service_layer/download.py
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Run tests with pytest
        run: |
          ~/.venv/bin/python -m pytest -vv tests/unit
